# Generated by Django 3.1 on 2020-08-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RanaProtfolio', '0002_service_workingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_class',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
