# Generated by Django 3.1 on 2020-08-26 08:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RanaProtfolio', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='workingprotfolio',
            name='client',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingprotfolio',
            name='deleiveri_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingprotfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='new'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingprotfolio',
            name='projects_link',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
    ]
